### PR TITLE
TurtleShroom Productions Proudly Presents: Ancient Rome Revived

### PR DESCRIPTION
**Pull request by TurtleShroom**
This is nothing short of a complete restructuring of this already incredible Mod. I have also added full support for the Vanilla Factions Expanded Classical Mod!

### CODE REVIEW

**Comment by emipa606** [comment]
There are some conflicts that cannot be solved easily. You think you can update the PR with the conflicts fixed? Then I can fix this and continue on with the AncientRimMediterranFactions.

**Comment by TurtleShroom** [comment]
> There are some conflicts that cannot be solved easily. You think you can update the PR with the conflicts fixed? Then I can fix this and continue on with the AncientRimMediterranFactions.

My pleasure. I will try that now.

**Comment by TurtleShroom** [comment]
Mlie, I believe that I have fixed the issue. Please check and see if anything more is needed.

**Comment by emipa606** [comment]
Should be added in 3834653
Fixed the missing VFE layers-patch for the outer-shell.
Also fixed the turret-graphic issues.

**Pull request merged**
